[package]
name = "file_info"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/zy97/file_info"

[dependencies]

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
